name: smart_task_manager
description: "smart-task-manager"
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cloud_firestore: ^6.1.2
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  riverpod_annotation: ^4.0.2

dev_dependencies:
  build_runner: ^2.11.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^4.0.3


flutter:

  uses-material-design: true
